<a href="https://colab.research.google.com/github/wrwills/pml/blob/master/course/Problem033_mf_collaborative_filtering/033.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Factorisation

![](https://miro.medium.com/max/1400/1*kxAP7W7aOGdcgpTFUMgSfg.jpeg "Logo Title Text 1")


In [19]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
import numpy as np

from scipy.sparse.linalg import svds

import pandas as pd

def display_matrix(data):
  df = pd.DataFrame(data) 
  df.rename(columns=lambda x: "item" + str(x + 1), inplace=True)
  df.rename(index = lambda x: "user" + str(x + 1), inplace=True)
  return df

A = [
    [3,1,1,3,1],
    [1,2,4,1,3],
    [3,1,1,3,1],
    [4,3,5,4,4],
    [1,5,5,1,5]
]

display_matrix(A)


item1  item2  item3  item4  item5
user1      3      1      1      3      1
user2      1      2      4      1      3
user3      3      1      1      3      1
user4      4      3      5      4      4
user5      1      5      5      1      5

items 1 and 4: comedies

items 3 and 5: action 

In [20]:
U, sigma, VT = svd(array(A))
Sigma = np.diag(sigma)

n = U.dot(Sigma.dot(VT))
display(U)
display(sigma)
display(VT)
display(n)

array([[-2.54796916e-01,  5.16683691e-01, -2.60991370e-01,
         7.25764262e-01, -2.70677366e-01],
       [-3.75561167e-01, -2.55315462e-01,  6.27509223e-01,
         4.01704239e-02, -6.31178530e-01],
       [-2.54796916e-01,  5.16683691e-01, -2.60991370e-01,
        -6.85593838e-01, -3.60501164e-01],
       [-6.30358083e-01,  2.61368229e-01,  3.66517853e-01,
        -4.01704239e-02,  6.31178530e-01],
       [-5.75985729e-01, -5.76694539e-01, -5.79365039e-01,
         1.24900090e-16,  3.12250226e-17]])

array([1.41648871e+01, 5.41845487e+00, 1.41291190e+00, 3.42609121e-16,
       2.66451462e-16])

array([[-0.35310982, -0.42582189, -0.56785186, -0.35310982, -0.49683688],
       [ 0.6115332 , -0.29097438, -0.28874025,  0.6115332 , -0.28985732],
       [-0.03661419, -0.75322172,  0.65383993, -0.03661419, -0.04969089],
       [ 0.28307163, -0.37410803, -0.37410803, -0.28307163,  0.74821606],
       [ 0.64797411,  0.16343148,  0.16343148, -0.64797411, -0.32686296]])

array([[3., 1., 1., 3., 1.],
       [1., 2., 4., 1., 3.],
       [3., 1., 1., 3., 1.],
       [4., 3., 5., 4., 4.],
       [1., 5., 5., 1., 5.]])

In [21]:
A = np.mat(A,np.float64)

U, sigma, VT = svds(A,k=2)
Sigma = np.diag(sigma)

n = U.dot(Sigma.dot(VT))
display(U)
display(sigma)
display(VT)

display(n)

array([[ 0.51668369,  0.25479692],
       [-0.25531546,  0.37556117],
       [ 0.51668369,  0.25479692],
       [ 0.26136823,  0.63035808],
       [-0.57669454,  0.57598573]])

array([ 5.41845487, 14.16488711])

array([[ 0.6115332 , -0.29097438, -0.28874025,  0.6115332 , -0.28985732],
       [ 0.35310982,  0.42582189,  0.56785186,  0.35310982,  0.49683688]])

array([[2.98649823, 0.72224361, 1.24110858, 2.98649823, 0.9816761 ],
       [1.0324627 , 2.66781786, 3.42029554, 1.0324627 , 3.0440567 ],
       [2.98649823, 0.72224361, 1.24110858, 2.98649823, 0.9816761 ],
       [4.01896093, 3.39006147, 4.66140413, 4.01896093, 4.0257328 ],
       [0.97002793, 4.38341891, 5.53522798, 0.97002793, 4.95932345]])

In [22]:
display(Sigma.dot(VT))

array([[ 3.31356506, -1.57663155, -1.56452602,  3.31356506, -1.57057879],
       [ 5.00176072,  6.03171906,  8.04355756,  5.00176072,  7.03763831]])

items:
1 and 4 should be comedy
3 and 5 should be action

users 1 and 3 should favour comedies
user 2 should favor action


## Missing ratings?


In [23]:
A = [
    [4., 1., None, None, 5.0],
    [3.5, 0.5, None, 2., 4.],
    [None, None, 3., 4., 1.],
    [0.5, 4., None, None, 0.5],
    [1.5, 5., None, None, None]
]

def average(xs):
    nxs = list(filter(lambda x: x is not None, xs))
    return sum(nxs) / len(nxs)


def normalise(xs):
    avg = average(xs)
    return [0.0 if x is None else x - avg for x in xs]

AA = [normalise(x) for x in A]

U, sigma, VT = svds(AA,k=2)

Sigma = np.diag(sigma)
n = U.dot(Sigma.dot(VT))