<a href="https://colab.research.google.com/github/wrwills/pml/blob/master/course/Problem033_mf_collaborative_filtering/033.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix Factorisation

![](https://miro.medium.com/max/1400/1*kxAP7W7aOGdcgpTFUMgSfg.jpeg "Logo Title Text 1")


In [1]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
import numpy as np

from scipy.sparse.linalg import svds

import pandas as pd

def display_matrix(data):
  df = pd.DataFrame(data) 
  df.rename(columns=lambda x: "item" + str(x + 1), inplace=True)
  df.rename(index = lambda x: "user" + str(x + 1), inplace=True)
  return df

A = [
    [3,1,1,3,1],
    [1,2,4,1,3],
    [3,1,1,3,1],
    [4,3,5,4,4],
    [1,5,5,1,5]
]

display_matrix(A)


item1  item2  item3  item4  item5
user1      3      1      1      3      1
user2      1      2      4      1      3
user3      3      1      1      3      1
user4      4      3      5      4      4
user5      1      5      5      1      5

items 1 and 4: comedies

items 3 and 5: action 

In [2]:
U, sigma, VT = svd(array(A))
Sigma = np.diag(sigma)

n = U.dot(Sigma.dot(VT))
display(U)
display(sigma)
display(VT)
display(n)

array([[-2.54796916e-01,  5.16683691e-01, -2.60991370e-01,
         7.25764262e-01, -2.70677366e-01],
       [-3.75561167e-01, -2.55315462e-01,  6.27509223e-01,
         4.01704239e-02, -6.31178530e-01],
       [-2.54796916e-01,  5.16683691e-01, -2.60991370e-01,
        -6.85593838e-01, -3.60501164e-01],
       [-6.30358083e-01,  2.61368229e-01,  3.66517853e-01,
        -4.01704239e-02,  6.31178530e-01],
       [-5.75985729e-01, -5.76694539e-01, -5.79365039e-01,
         1.24900090e-16,  3.12250226e-17]])

array([1.41648871e+01, 5.41845487e+00, 1.41291190e+00, 3.42609121e-16,
       2.66451462e-16])

array([[-0.35310982, -0.42582189, -0.56785186, -0.35310982, -0.49683688],
       [ 0.6115332 , -0.29097438, -0.28874025,  0.6115332 , -0.28985732],
       [-0.03661419, -0.75322172,  0.65383993, -0.03661419, -0.04969089],
       [ 0.28307163, -0.37410803, -0.37410803, -0.28307163,  0.74821606],
       [ 0.64797411,  0.16343148,  0.16343148, -0.64797411, -0.32686296]])

array([[3., 1., 1., 3., 1.],
       [1., 2., 4., 1., 3.],
       [3., 1., 1., 3., 1.],
       [4., 3., 5., 4., 4.],
       [1., 5., 5., 1., 5.]])

In [3]:
A = np.mat(A,np.float64)

U, sigma, VT = svds(A,k=2)
Sigma = np.diag(sigma)

n = U.dot(Sigma.dot(VT))
display(U)
display(sigma)
display(VT)

display(n)

array([[ 0.51668369,  0.25479692],
       [-0.25531546,  0.37556117],
       [ 0.51668369,  0.25479692],
       [ 0.26136823,  0.63035808],
       [-0.57669454,  0.57598573]])

array([ 5.41845487, 14.16488711])

array([[ 0.6115332 , -0.29097438, -0.28874025,  0.6115332 , -0.28985732],
       [ 0.35310982,  0.42582189,  0.56785186,  0.35310982,  0.49683688]])

array([[2.98649823, 0.72224361, 1.24110858, 2.98649823, 0.9816761 ],
       [1.0324627 , 2.66781786, 3.42029554, 1.0324627 , 3.0440567 ],
       [2.98649823, 0.72224361, 1.24110858, 2.98649823, 0.9816761 ],
       [4.01896093, 3.39006147, 4.66140413, 4.01896093, 4.0257328 ],
       [0.97002793, 4.38341891, 5.53522798, 0.97002793, 4.95932345]])

In [4]:
display(Sigma.dot(VT))

array([[ 3.31356506, -1.57663155, -1.56452602,  3.31356506, -1.57057879],
       [ 5.00176072,  6.03171906,  8.04355756,  5.00176072,  7.03763831]])

items:
1 and 4 should be comedy
3 and 5 should be action

users 1 and 3 should favour comedies
user 2 should favor action


## Missing ratings?


In [6]:
A = [
    [4., 1., None, None, 5.0],
    [3.5, 0.5, None, 2., 4.],
    [None, None, 3., 4., 1.],
    [0.5, 4., None, None, 0.5],
    [1.5, 5., None, None, None]
]

def average(xs):
    nxs = list(filter(lambda x: x is not None, xs))
    return sum(nxs) / len(nxs)


def normalise(xs):
    avg = average(xs)
    return [0.0 if x is None else x - avg for x in xs]

AA = [normalise(x) for x in A]

U, sigma, VT = svds(AA,k=2)

Sigma = np.diag(sigma)
n = U.dot(Sigma.dot(VT))

display(U)
display(Sigma.dot(VT))

display(n)

array([[-0.09697977, -0.53585916],
       [-0.14887612, -0.50606805],
       [ 0.82946082,  0.17085387],
       [-0.13675039,  0.5288954 ],
       [-0.51159057,  0.38448498]])

array([[ 0.84129631, -0.69032935,  0.27648694,  1.18038582, -1.60783971],
       [-2.15320084,  4.16941212,  0.05695129,  0.48083919, -2.55400176]])

array([[ 1.07222366, -2.16726967, -0.05733151, -0.37213563,  1.52451316],
       [ 0.96441723, -2.00723272, -0.06998353, -0.41906861,  1.53186763],
       [ 0.32993962,  0.13975906,  0.23906543,  1.06123702, -1.77000113],
       [-1.25386562,  2.2995857 , -0.00768842,  0.09289542, -1.13092709],
       [-1.25827264,  1.95624232, -0.11955119, -0.4189988 , -0.15941969]])

## Let's try applying this to some real world data anyway



In [7]:
!wget  http://files.grouplens.org/datasets/movielens/ml-1m.zip
!unzip ml-1m.zip
!pwd

--2021-01-14 10:01:06--  http://files.grouplens.org/datasets/movielens/ml-1m.zip
Resolving files.grouplens.org (files.grouplens.org)... 128.101.65.152
Connecting to files.grouplens.org (files.grouplens.org)|128.101.65.152|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5917549 (5.6M) [application/zip]
Saving to: ‘ml-1m.zip’

ml-1m.zip           100%[===================>]   5.64M  14.9MB/s    in 0.4s    

2021-01-14 10:01:06 (14.9 MB/s) - ‘ml-1m.zip’ saved [5917549/5917549]

Archive:  ml-1m.zip
   creating: ml-1m/
  inflating: ml-1m/movies.dat        
  inflating: ml-1m/ratings.dat       
  inflating: ml-1m/README            
  inflating: ml-1m/users.dat         
/content


In [8]:
import pandas as pd
import numpy as np

#from d2l import mxnet as d2l
#from mxnet import gluon, np
import os
import pandas as pd
from scipy.sparse.linalg import svds
from numpy import zeros


# http://files.grouplens.org/datasets/movielens/ml-1m.zip
dir = '/content/ml-1m/'
ratings_list = [i.strip().split("::") for i in open(dir + 'ratings.dat', 'r').readlines()]
users_list = [i.strip().split("::") for i in open(dir + 'users.dat', 'r').readlines()]
movies_list = [i.strip().split("::") for i in open(dir + 'movies.dat', 'r', encoding = "ISO-8859-1").readlines()]

ratings_df = pd.DataFrame(ratings_list, columns = ['UserID', 'MovieID', 'Rating', 'Timestamp'], dtype = int)
movies_df = pd.DataFrame(movies_list, columns = ['MovieID', 'Title', 'Genres'])
movies_df['MovieID'] = movies_df['MovieID'].apply(pd.to_numeric)



In [9]:
R_df = ratings_df.pivot(index = 'UserID', columns ='MovieID', values = 'Rating').fillna(0)
R_df.head()
R_df = R_df.apply(pd.to_numeric)

R = R_df.values
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

U, sigma, Vt = svds(R_demeaned, k = 20)

Sigma = np.diag(sigma)
n = U.dot(Sigma.dot(Vt))
display(U)
display(sigma)
display(Vt)
display(n)


array([[-0.00574605,  0.0025163 ,  0.00160289, ...,  0.00295139,
         0.00195703,  0.0054689 ],
       [ 0.02243342, -0.00995284, -0.008162  , ..., -0.01498024,
        -0.00347841,  0.02689629],
       [ 0.01406056, -0.01308128,  0.0108737 , ..., -0.00800385,
        -0.00432385,  0.00705568],
       ...,
       [-0.00677375, -0.00013937, -0.01111045, ...,  0.00474073,
        -0.00339477,  0.00431568],
       [ 0.01816663, -0.00935234,  0.00898066, ...,  0.02620587,
         0.00759581,  0.00699538],
       [ 0.01434938, -0.00401954, -0.00149913, ..., -0.00042638,
        -0.02412542,  0.01850617]])

array([ 212.55518526,  215.46630906,  221.6502159 ,  231.38108343,
        239.08619469,  244.8772772 ,  252.13622776,  256.26466285,
        275.38648118,  287.89180228,  315.0835415 ,  335.08085421,
        345.17197178,  362.26793969,  415.93557804,  434.97695433,
        497.2191638 ,  574.46932602,  670.41536276, 1544.10679346])

array([[-0.06998523,  0.0407485 ,  0.00421439, ...,  0.00145469,
        -0.00489998, -0.00799834],
       [ 0.1181127 ,  0.01283735,  0.00218896, ..., -0.00552797,
        -0.00312608,  0.00085089],
       [ 0.0087521 , -0.01336816,  0.00585148, ...,  0.00047578,
         0.00828728,  0.00835374],
       ...,
       [ 0.03287652, -0.01895066,  0.0061194 , ...,  0.00161115,
         0.00369017,  0.00926893],
       [-0.01776333, -0.05395807, -0.00139293, ...,  0.00118251,
        -0.0048817 , -0.00403605],
       [ 0.07625855,  0.02802877, -0.00530375, ..., -0.01005848,
        -0.00772388,  0.00147574]])

array([[ 3.14685339, -0.08409309, -0.09507561, ..., -0.0674051 ,
        -0.07906638, -0.22636765],
       [ 4.85019427,  0.97521544, -0.68644255, ..., -0.54266573,
        -0.65437844, -0.82051896],
       [-0.06973815,  0.81018783, -0.11237976, ..., -0.0628956 ,
        -0.01524059, -0.18837905],
       ...,
       [ 1.79122886,  0.03245695, -0.07569502, ..., -0.03169412,
        -0.04187531, -0.120584  ],
       [ 1.23775475, -0.35082098,  0.02009478, ..., -0.01832998,
        -0.10015102, -0.14332423],
       [-1.19420181,  3.03196482,  0.16368347, ..., -0.29587815,
         0.03992397,  0.15770374]])

In [14]:
R[0]

array([5, 0, 0, ..., 0, 0, 0])

In [12]:
R_demeaned[0]


array([ 4.94009714, -0.05990286, -0.05990286, ..., -0.05990286,
       -0.05990286, -0.05990286])

In [13]:
n[0]

array([ 3.14685339, -0.08409309, -0.09507561, ..., -0.0674051 ,
       -0.07906638, -0.22636765])

https://github.com/beckernick/matrix_factorization_recommenders/blob/master/matrix_factorization_recommender.ipynb